name: Publish

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Pull in dev.to posts
      uses: gautamkrishnar/blog-post-workflow@v1
      with:
        template: "TEMPLATE.md"
        feed_list: "https://dev.to/feed/arafatiqbal"
    - name: Generate README.md
      uses: actions-js/profile-readme@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: arafatiqbal
        template: "TEMPLATE.md"
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
