name: Publish

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Pull in dev.to posts
      uses: gautamkrishnar/blog-post-workflow@v1
      with:
        feed_list: "https://dev.to/feed/arafatiqbal"
